export const SAVE_FUEL_SAVINGS_REQUEST = "SAVE_FUEL_SAVINGS_REQUEST";
export const SAVE_FUEL_SAVINGS_SUCCESS = "SAVE_FUEL_SAVINGS_SUCCESS";
export const CALCULATE_FUEL_SAVINGS = "CALCULATE_FUEL_SAVINGS";
